export interface SiteInfo {
  account_name: string;
  account_slug: string;
  admin_url: string;
  build_settings: {
    allowed_branches: string[];
    cmd: string;
    deploy_key_id: string;
    dir: string;
    env: Record<string, unknown>;
    id: number;
    private_logs: boolean;
    provider: string;
    public_repo: boolean;
    repo_branch: string;
    repo_path: string;
    repo_url: string;
  };
  capabilities: Record<string, unknown>;
  created_at: string;
  custom_domain: string;
  deploy_hook: string;
  deploy_url: string;
  domain_aliases: string[];
  force_ssl: boolean;
  git_provider: string;
  id: string;
  managed_dns: boolean;
  name: string;
  notification_email: string;
  password: string;
  plan: string;
  processing_settings: {
    css: {
      bundle: boolean;
      minify: boolean;
    };
    html: Record<string, unknown>;
    images: Record<string, unknown>;
    js: {
      bundle: boolean;
      minify: boolean;
    };
    skip: boolean;
  };
  published_deploy: {
    admin_url: string;
    branch: string;
    build_id: string;
    commit_ref: string;
    commit_url: string;
    context: string;
    created_at: string;
    deploy_ssl_url: string;
    deploy_url: string;
    draft: boolean;
    error_message: string;
    id: string;
    locked: boolean;
    name: string;
    published_at: string;
    required: string[];
    required_functions: string[];
    review_id: number;
    review_url: string;
    screenshot_url: string;
    site_id: string;
    skipped: boolean;
    ssl_url: string;
    state: string;
    title: string;
    updated_at: string;
    url: string;
    user_id: string;
  };
  screenshot_url: string;
  session_id: string;
  ssl: boolean;
  ssl_url: string;
  state: string;
  updated_at: string;
  url: string;
  user_id: string;
}