codecov:
  strict_yaml_branch: main
coverage:
  range: [80, 100]
  parsers:
    javascript:
      enable_partials: true
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true
comment: false
