[build]
  command = "pushd .. && npm ci --no-verify && popd && npm run build"
  publish = "dist"

[functions]
  node_bundler = "esbuild"

#####################
#  Redirect Rules   #
#####################
[[redirects]]
  # Telemetry link
  from = "/telemetry/*"
  to = "/.netlify/functions/telemetry"
  status = 200
  force = true
[[redirects]]
  # Bugsnag link
  from = "/report-error"
  to = "/.netlify/functions/error-reporting"
  status = 200
  force = true
[[redirects]]
  # Old CLI download links.
  from = "/download/latest/mac"
  to = "https://github.com/netlify/netlifyctl/releases/download/v0.4.0/netlifyctl-darwin-amd64-0.4.0.tar.gz"
  status = 302
  force = false
[[redirects]]
  # Old CLI download links.
  from = "/download/latest/linux"
  to = "https://github.com/netlify/netlifyctl/releases/download/v0.4.0/netlifyctl-linux-amd64-0.4.0.tar.gz"
  status = 302
  force = false
[[redirects]]
  # Old CLI download links.
  from = "/download/latest/windows"
  to = "https://github.com/netlify/netlifyctl/releases/download/v0.4.0/netlifyctl-windows-amd64-0.4.0.zip"
  status = 302
  force = false
[[redirects]]
  # Old CLI download links.
  from = "/download/latest/source-zip"
  to = "https://github.com/netlify/netlifyctl/archive/v0.4.0.zip"
  status = 302
  force = false
[[redirects]]
  # Old CLI download links.
  from = "/download/latest/source-tar"
  to = "https://github.com/netlify/netlifyctl/archive/v0.4.0.tar.gz"
  status = 302
  force = false
