const DETECTORS = {
  'angular': require('./angular'),
  'brunch': require('./brunch'),
  'create-react-app': require('./create-react-app'),
  'docusaurus': require('./docusaurus'),
  'eleventy': require('./eleventy'),
  'ember': require('./ember'),
  'expo': require('./expo'),
  'gatsby': require('./gatsby'),
  'gridsome': require('./gridsome'),
  'hexo': require('./hexo'),
  'hugo': require('./hugo'),
  'jekyll': require('./jekyll'),
  'middleman': require('./middleman'),
  'next': require('./next'),
  'nuxt': require('./nuxt'),
  'parcel': require('./parcel'),
  'phenomic': require('./phenomic'),
  'quasar': require('./quasar'),
  'quasar-v0.17': require('./quasar-v0.17'),
  'react-static': require('./react-static'),
  'sapper': require('./sapper'),
  'stencil': require('./stencil'),
  'svelte': require('./svelte'),
  'vue': require('./vue'),
  'vuepress': require('./vuepress'),
}

module.exports = { DETECTORS }
