const sample = require('lodash/sample')
const fetch = require('node-fetch')
const { v4: uuidv4 } = require('uuid')

const getTemplatesFromGitHub = async (token) => {
  const getPublicGitHubReposFromOrg = new URL(`https://api.github.com/orgs/netlify-templates/repos`)
  // GitHub returns 30 by default and we want to avoid our limit
  // due to our archived repositories at any given time
  const REPOS_PER_PAGE = 70

  getPublicGitHubReposFromOrg.searchParams.set('type', 'public')
  getPublicGitHubReposFromOrg.searchParams.set('sort', 'full_name')
  getPublicGitHubReposFromOrg.searchParams.set('per_page', REPOS_PER_PAGE)

  const templates = await fetch(getPublicGitHubReposFromOrg, {
    method: 'GET',
    headers: {
      Authorization: `token ${token}`,
    },
  })
  const allTemplates = await templates.json()

  return allTemplates
}

const validateTemplate = async ({ ghToken, templateName }) => {
  const response = await fetch(`https://api.github.com/repos/${templateName}`, {
    headers: {
      Authorization: `token ${ghToken}`,
    },
  })

  if (response.status === 404) {
    return { exists: false }
  }

  if (!response.ok) {
    throw new Error(`Error fetching template ${templateName}: ${await response.text()}`)
  }

  const data = await response.json()
  return { exists: true, isTemplate: data.is_template }
}

const createRepo = async (templateName, ghToken, siteName) => {
  const resp = await fetch(`https://api.github.com/repos/${templateName}/generate`, {
    method: 'POST',
    headers: {
      Authorization: `token ${ghToken}`,
    },
    body: JSON.stringify({
      name: siteName,
    }),
  })

  const data = await resp.json()
  return data
}

const SITE_NAME_SUGGESTION_SUFFIX_LENGTH = 6

// Adapted from https://github.com/netlify/bitballoon/blob/main/lib/name_generator.rb
const generateSiteName = () => {
  const left = [
    'admirable',
    'adorable',
    'aesthetic',
    'amazing',
    'animated',
    'aquamarine',
    'astonishing',
    'astounding',
    'beamish',
    'beautiful',
    'bejewelled',
    'benevolent',
    'bespoke',
    'boisterous',
    'bright',
    'brilliant',
    'bucolic',
    'calm',
    'candid',
    'capable',
    'celadon',
    'celebrated',
    'cerulean',
    'charming',
    'cheerful',
    'cheery',
    'chic',
    'chimerical',
    'chipper',
    'classy',
    'clever',
    'clinquant',
    'comforting',
    'comfy',
    'cool',
    'coruscating',
    'cosmic',
    'courageous',
    'cozy',
    'creative',
    'curious',
    'cute',
    'dainty',
    'dancing',
    'dapper',
    'darling',
    'dashing',
    'dazzling',
    'deft',
    'delicate',
    'delightful',
    'deluxe',
    'dreamy',
    'dulcet',
    'dynamic',
    'earnest',
    'eclectic',
    'effervescent',
    'effortless',
    'effulgent',
    'elaborate',
    'elegant',
    'eloquent',
    'enchanting',
    'endearing',
    'ephemeral',
    'euphonious',
    'exquisite',
    'extraordinary',
    'fabulous',
    'famous',
    'fanciful',
    'fancy',
    'fantastic',
    'fascinating',
    'fastidious',
    'flourishing',
    'fluffy',
    'frabjous',
    'friendly',
    'frolicking',
    'funny',
    'gentle',
    'genuine',
    'gilded',
    'gleaming',
    'gleeful',
    'glistening',
    'glittering',
    'glittery',
    'glowing',
    'golden',
    'gorgeous',
    'graceful',
    'grand',
    'gregarious',
    'guileless',
    'harmonious',
    'heartfelt',
    'helpful',
    'heroic',
    'hilarious',
    'idyllic',
    'illustrious',
    'imaginative',
    'incandescent',
    'incomparable',
    'incredible',
    'inquisitive',
    'inspiring',
    'iridescent',
    'jade',
    'jazzy',
    'jocular',
    'jolly',
    'jovial',
    'joyful',
    'kaleidoscopic',
    'keen',
    'lambent',
    'leafy',
    'legendary',
    'lighthearted',
    'lively',
    'loquacious',
    'lovely',
    'lucent',
    'lucky',
    'luminous',
    'lustrous',
    'luxury',
    'magenta',
    'magical',
    'magnificent',
    'majestic',
    'marvelous',
    'meek',
    'mellifluous',
    'mellow',
    'melodic',
    'melodious',
    'merry',
    'monumental',
    'moonlit',
    'musical',
    'neon',
    'nimble',
    'ornate',
    'papaya',
    'peaceful',
    'peppy',
    'phenomenal',
    'playful',
    'poetic',
    'polite',
    'precious',
    'preeminent',
    'prismatic',
    'profound',
    'quiet',
    'rad',
    'radiant',
    'rainbow',
    'regal',
    'relaxed',
    'reliable',
    'remarkable',
    'resilient',
    'resonant',
    'resplendent',
    'roaring',
    'rococo',
    'sage',
    'scintillating',
    'sensational',
    'serene',
    'shimmering',
    'shiny',
    'silly',
    'silver',
    'singular',
    'snazzy',
    'soft',
    'sparkling',
    'sparkly',
    'spectacular',
    'spiffy',
    'splendid',
    'splendorous',
    'spontaneous',
    'sprightly',
    'stalwart',
    'starlit',
    'startling',
    'stately',
    'statuesque',
    'steady',
    'stellar',
    'stellular',
    'stirring',
    'storied',
    'strong',
    'stunning',
    'stupendous',
    'subtle',
    'sunny',
    'super',
    'superb',
    'superlative',
    'sweet',
    'symphonious',
    'tangerine',
    'taupe',
    'teal',
    'thriving',
    'thunderous',
    'timely',
    'tiny',
    'tourmaline',
    'tranquil',
    'transcendent',
    'tubular',
    'ubiquitous',
    'unique',
    'unrivaled',
    'velvety',
    'venerable',
    'verdant',
    'vermillion',
    'visionary',
    'vocal',
    'voluble',
    'warm',
    'whimsical',
    'willowy',
    'wonderful',
    'wondrous',
    'zesty',
    'zingy',
    'zippy',
  ]

  const right = [
    'alfajores',
    'alpaca',
    'arithmetic',
    'axolotl',
    'babka',
    'baklava',
    'banoffee',
    'basbousa',
    'bavarois',
    'begonia',
    'beignet',
    'beijinho',
    'belekoy',
    'bienenstitch',
    'biscochitos',
    'biscotti',
    'biscuit',
    'blancmange',
    'blini',
    'boba',
    'bombolone',
    'bonbon',
    'brigadeiros',
    'brioche',
    'bubblegum',
    'bublanina',
    'bunny',
    'buttercream',
    'cactus',
    'cajeta',
    'cannoli',
    'capybara',
    'caramel',
    'cascaron',
    'cassata',
    'cat',
    'cendol',
    'centaur',
    'chaja',
    'chebakia',
    'cheesecake',
    'chimera',
    'choux',
    'churros',
    'clafoutis',
    'cobbler',
    'cocada',
    'concha',
    'conkies',
    'cranachan',
    'crepe',
    'creponne',
    'crisp',
    'croissant',
    'croquembouche',
    'crostata',
    'crumble',
    'cuchufli',
    'cucurucho',
    'cupcake',
    'custard',
    'daffodil',
    'daifuku',
    'dango',
    'dasik',
    'dieffenbachia',
    'dodol',
    'dolphin',
    'donut',
    'douhua',
    'dragon',
    'druid',
    'duckanoo',
    'dusk',
    'eclair',
    'elf',
    'empanada',
    'entremet',
    'fairy',
    'faloodeh',
    'faun',
    'fenglisu',
    'figolla',
    'flan',
    'florentine',
    'fox',
    'frangipane',
    'frangollo',
    'froyo',
    'fudge',
    'ganache',
    'gaufre',
    'gecko',
    'gelato',
    'genie',
    'gingersnap',
    'gnome',
    'granita',
    'griffin',
    'gumdrop',
    'gumption',
    'halva',
    'hamster',
    'haupia',
    'heliotrope',
    'horse',
    'hotteok',
    'hummingbird',
    'jalebi',
    'jelly',
    'kangaroo',
    'kashata',
    'kataifi',
    'kelpie',
    'khapse',
    'kheer',
    'kitsune',
    'kitten',
    'kleicha',
    'klepon',
    'kringle',
    'kulfi',
    'lamington',
    'lebkuchen',
    'licorice',
    'liger',
    'lily',
    'llama',
    'lokum',
    'lollipop',
    'lolly',
    'longma',
    'maamoul',
    'macaron',
    'madeleine',
    'malabi',
    'malasada',
    'manatee',
    'mandazi',
    'marigold',
    'marshmallow',
    'marzipan',
    'medovik',
    'meerkat',
    'melba',
    'melomakarona',
    'meringue',
    'mermaid',
    'mochi',
    'monstera',
    'moonbeam',
    'mooncake',
    'mousse',
    'moxie',
    'muffin',
    'naiad',
    'narwhal',
    'nasturtium',
    'nougat',
    'otter',
    'paletas',
    'palmier',
    'panda',
    'paprenjak',
    'parfait',
    'pasca',
    'pastelito',
    'pavlova',
    'pegasus',
    'peony',
    'phoenix',
    'pie',
    'pika',
    'piroshki',
    'pithivier',
    'pixie',
    'platypus',
    'pony',
    'pothos',
    'praline',
    'profiterole',
    'pudding',
    'puffpuff',
    'puppy',
    'queijadas',
    'quokka',
    'rabanadas',
    'raindrop',
    'rolypoly',
    'rugelach',
    'sable',
    'salamander',
    'salmiakki',
    'sawine',
    'scone',
    'seahorse',
    'selkie',
    'semifreddo',
    'semolina',
    'sfogliatella',
    'sherbet',
    'shortbread',
    'smakager',
    'snickerdoodle',
    'sopapillas',
    'sorbet',
    'souffle',
    'speculoos',
    'sprinkles',
    'sprite',
    'squirrel',
    'starburst',
    'stardust',
    'starlight',
    'starship',
    'stroopwafel',
    'strudel',
    'sunburst',
    'sundae',
    'sunflower',
    'sunshine',
    'swan',
    'syrniki',
    'taffy',
    'taiyaki',
    'tanuki',
    'tapioca',
    'tarsier',
    'tartufo',
    'tiramisu',
    'toffee',
    'torrone',
    'torte',
    'travesseiro',
    'treacle',
    'trifle',
    'truffle',
    'tulumba',
    'twilight',
    'unicorn',
    'vacherin',
    'valkyrie',
    'wisp',
    'yeot',
    'youtiao',
    'zabaione',
    'zuccutto',
  ]

  const suffix = `${uuidv4().slice(0, SITE_NAME_SUGGESTION_SUFFIX_LENGTH)}`

  return `${sample(left)}-${sample(right)}-${suffix}`
}

module.exports = { getTemplatesFromGitHub, createRepo, validateTemplate, generateSiteName }
