name: Docsearch

on:
  schedule:
    - cron: '0 */12 * * *'

jobs:
  run-search:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: darrenjennings/algolia-docsearch-action@e3b8c5540e90a964b655be6ca73c1ee1aeba2719
        with:
          algolia_application_id: '4RTNPM1QF9'
          algolia_api_key: ${{ secrets.ALGOLIA_API_KEY }}
          file: 'site/algolia/config.json'
