name: Docsearch

on:
  schedule:
    - cron: '0 */2 * * *'

jobs:
  run-search:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: darrenjennings/algolia-docsearch-action@1eaef43429fb70fbf737cfd3e3e455864c1af4d2
        with:
          algolia_application_id: '4RTNPM1QF9'
          algolia_api_key: ${{ secrets.ALGOLIA_API_KEY }}
          file: 'site/algolia/config.json'
